function _precompile_()
    precompile(Tuple{getfield(Gloria, Symbol("##call#5#6")), Bool, Float64, Type{Gloria.Layer{Array{Parallax.Object, 1}}}, Array{Parallax.Object, 1}, Float64, Float64, Array{Float64, 2}})
    precompile(Tuple{typeof(Gloria.__init__)})
    precompile(Tuple{getfield(Gloria, Symbol("##call#5#6")), Bool, Float64, Type{Gloria.Layer{Array{Parallax.Controls, 1}}}, Array{Parallax.Controls, 1}, Float64, Float64, Array{Float64, 2}})
    precompile(Tuple{getfield(Gloria, Symbol("##render!#23")), Float64, Float64, Float64, Int64, Int64, Symbol, typeof(identity), Gloria.Layer{Array{Parallax.Object, 1}}, Gloria.Texture, Array{Float64, 1}})
    precompile(Tuple{typeof(Gloria.onevent!), Parallax.Controls, Base.Val{:mousemotion}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Parallax.Controls, Base.Val{:mousebutton_up}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Parallax.Controls, Base.Val{:mousebutton_down}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Object, 1}}, Base.Val{:mousemotion}, Gloria.Event})
    precompile(Tuple{getfield(Gloria, Symbol("##update!#21")), Float64, Float64, typeof(identity), Gloria.Layer{Array{Parallax.Object, 1}}})
    precompile(Tuple{getfield(Gloria, Symbol("#kw##update!")), NamedTuple{(:t, :dt), Tuple{Float64, Float64}}, typeof(Gloria.update!), Gloria.Layer{Array{Parallax.Controls, 1}}})
    precompile(Tuple{typeof(Gloria.geteventdata), Array{UInt8, 1}, Base.Pair{Symbol, DataType}, Base.Pair{Symbol, DataType}})
    precompile(Tuple{typeof(Gloria.bitcat), Type{Int32}, Array{UInt8, 1}})
    precompile(Tuple{typeof(Gloria.bitcat), Type{UInt8}, Array{UInt8, 1}})
    precompile(Tuple{getfield(Gloria, Symbol("##render!#24")), (Base.Iterators).Pairs{Symbol, Float64, Tuple{Symbol}, NamedTuple{(:angle,), Tuple{Float64}}}, typeof(identity), Gloria.Layer{Array{Parallax.Object, 1}}, Gloria.Texture, Float64, Float64})
    precompile(Tuple{typeof(Gloria.bitcat), Type{UInt32}, Array{UInt8, 1}})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Object, 1}}, Base.Val{:mousebutton_up}, Gloria.Event})
    precompile(Tuple{getfield(Gloria, Symbol("#kw##update!")), NamedTuple{(:t, :dt), Tuple{Float64, Float64}}, typeof(Gloria.update!), Gloria.Layer{Array{Parallax.Object, 1}}})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Controls, 1}}, Base.Val{:quit}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Object, 1}}, Base.Val{:mousebutton_down}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Object, 1}}, Base.Val{:quit}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.eventtype), Array{UInt8, 1}})
    precompile(Tuple{typeof(Gloria.getmousestate)})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Controls, 1}}, Base.Val{:mousebutton_down}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Controls, 1}}, Base.Val{:mousebutton_up}, Gloria.Event})
    precompile(Tuple{typeof(Gloria.onevent!), Gloria.Layer{Array{Parallax.Controls, 1}}, Base.Val{:mousemotion}, Gloria.Event})
end
