function _precompile_()
    precompile(Tuple{typeof(Base.ht_keyindex), Base.Dict{String, Gloria.AbstractResource}, String})
    precompile(Tuple{typeof(Base.stale_cachefile), String, String})
    precompile(Tuple{typeof(Base.rehash!), Base.Dict{String, Gloria.AbstractResource}, Int64})
    precompile(Tuple{typeof(Base.exp), Float64})
    precompile(Tuple{getfield(Base, Symbol("##649#650")), String})
    precompile(Tuple{typeof(Base.implicit_manifest_uuid_path), String, Base.PkgId})
    precompile(Tuple{typeof(Base.throw_boundserror), Array{Int64, 1}, Tuple{}})
    precompile(Tuple{typeof(Base._tryrequire_from_serialized), Base.PkgId, UInt64, Nothing})
    precompile(Tuple{typeof(Base.implicit_manifest_deps_get), String, Base.PkgId, String})
    precompile(Tuple{typeof(Base.vect), Symbol})
    precompile(Tuple{typeof(Base.getindex), Array{UInt8, 1}, Base.StepRange{Int64, Int64}})
    precompile(Tuple{typeof(Base.compilecache), Base.PkgId, String})
    precompile(Tuple{typeof(Base.explicit_project_deps_get), String, String})
    precompile(Tuple{typeof(Base._tryrequire_from_serialized), Base.PkgId, UInt64, String})
    precompile(Tuple{typeof(Base.throw_boundserror), Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}}, typeof(Base.round), Tuple{Base.RefValue{Type{Int64}}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(+)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(*)), Tuple{Base.Broadcast.Extruded{Array{Float64, 1}, Tuple{Bool}, Tuple{Int64}}, Float64}}, Base.Broadcast.Extruded{Array{Float64, 1}, Tuple{Bool}, Tuple{Int64}}}}}}, Tuple{Int64}})
    precompile(Tuple{typeof(Base.permutedims!), Array{UInt32, 2}, Array{UInt32, 2}, Tuple{Int64, Int64}})
    precompile(Tuple{typeof(Base.copyto!), Array{Task, 1}, Int64, Array{Task, 1}, Int64, Int64})
    precompile(Tuple{typeof(Base.project_file_name_uuid_path), String, String})
    precompile(Tuple{typeof(Base.CoreLogging.log_record_id), Module, Base.CoreLogging.LogLevel, Tuple{Expr}})
    precompile(Tuple{typeof(Base.fill!), Array{Float64, 1}, Int64})
    precompile(Tuple{typeof(Base.throw_boundserror), Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}}, typeof(Base.wait), Tuple{Base.Broadcast.Extruded{Array{Task, 1}, Tuple{Bool}, Tuple{Int64}}}}, Tuple{Int64}})
    precompile(Tuple{typeof(Base.manifest_uuid_path), String, Base.PkgId})
    precompile(Tuple{typeof(Base._require), Base.PkgId})
    precompile(Tuple{typeof(Base.copyto!), Array{Parallax.Object, 1}, Int64, Array{Parallax.Object, 1}, Int64, Int64})
    precompile(Tuple{typeof(Base.create_expr_cache), String, String, Array{Base.Pair{Base.PkgId, UInt64}, 1}, Nothing})
    precompile(Tuple{typeof(Base.CoreLogging.log_record_id), Nothing, Base.CoreLogging.LogLevel, Tuple{Expr, Expr, Expr}})
    precompile(Tuple{typeof(Base.fill!), Array{UInt32, 2}, UInt32})
    precompile(Tuple{typeof(Base._require_search_from_serialized), Base.PkgId, String})
    precompile(Tuple{typeof(Base.vect), Task, Task})
    precompile(Tuple{typeof(Base.vect), Parallax.Controls})
    precompile(Tuple{typeof(Base.setindex!), Base.Dict{Symbol, Any}, Int32, Symbol})
    precompile(Tuple{typeof(Base.setindex!), Base.Dict{Symbol, Any}, UInt32, Symbol})
    precompile(Tuple{typeof(Base.throw_boundserror), Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}}, typeof(Base.schedule), Tuple{Base.Broadcast.Extruded{Array{Task, 1}, Tuple{Bool}, Tuple{Int64}}}}, Tuple{Int64}})
    precompile(Tuple{typeof(Base.setindex!), Base.Dict{Symbol, Any}, UInt8, Symbol})
    precompile(Tuple{typeof(Base.require), Module, Symbol})
    precompile(Tuple{typeof(Base.isassigned), Core.SimpleVector, Int64})
    precompile(Tuple{typeof(Base.diff_names), Tuple{Symbol, Symbol}, Tuple{Symbol, Symbol, Symbol, Symbol, Symbol, Symbol}})
    precompile(Tuple{typeof(Base.collect), Tuple{Float64, Float64}})
    precompile(Tuple{typeof(Base.setindex!), Base.Dict{String, Gloria.AbstractResource}, Gloria.Texture, String})
    precompile(Tuple{typeof(Base.ht_keyindex2!), Base.Dict{String, Gloria.AbstractResource}, String})
    precompile(Tuple{typeof(Base.implicit_project_deps_get), String, String})
    precompile(Tuple{getfield(Base.Cartesian, Symbol("#@ntuple")), LineNumberNode, Module, Int64, Int})
    precompile(Tuple{typeof(Base._compute_eltype), Type{Tuple{Int64, Float64}}})
    precompile(Tuple{typeof(Base.haskey), Base.Dict{Symbol, Function}, Expr})
    precompile(Tuple{typeof(Base.load_path_setup_code), Bool})
    precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.round), Tuple{Base.RefValue{Type{Int64}}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(+)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(*)), Tuple{Array{Float64, 1}, Float64}}, Array{Float64, 1}}}}}})
    precompile(Tuple{getfield(Base, Symbol("##s549#398")), Int, Int, Int, Int, Int, Int})
    precompile(Tuple{typeof(Base.iterate), Array{Gloria.Layer{Array{Parallax.Object, 1}}, 1}})
    precompile(Tuple{typeof(Base.require), Base.PkgId})
    precompile(Tuple{typeof(Base.locate_package), Base.PkgId})
    precompile(Tuple{typeof(Base.identify_package), Base.PkgId, String})
    precompile(Tuple{typeof((Base.Broadcast).broadcasted), typeof(identity), Array{Float64, 1}, Float64})
    precompile(Tuple{typeof(Base.iterate), Array{Gloria.Layer{Array{Parallax.Object, 1}}, 1}, Int64})
    precompile(Tuple{typeof((Base.Broadcast).broadcasted), typeof(identity), (Base.Broadcast).Broadcasted{(Base.Broadcast).DefaultArrayStyle{1}, Nothing, typeof(Base.:*), Tuple{Array{Float64, 1}, Float64}}, Array{Float64, 1}})
    precompile(Tuple{typeof((Base.Broadcast).broadcasted), typeof(identity), Type{Int}, (Base.Broadcast).Broadcasted{(Base.Broadcast).DefaultArrayStyle{1}, Nothing, typeof(Base.:+), Tuple{(Base.Broadcast).Broadcasted{(Base.Broadcast).DefaultArrayStyle{1}, Nothing, typeof(Base.:*), Tuple{Array{Float64, 1}, Float64}}, Array{Float64, 1}}}})
    precompile(Tuple{typeof(Base.vect), Gloria.Layer{Array{Parallax.Controls, 1}}, Int})
    precompile(Tuple{typeof(Base.indexed_iterate), Array{Int64, 1}, Int64})
    precompile(Tuple{typeof(Base._require_from_serialized), String})
    precompile(Tuple{typeof(Base.setproperty!), Gloria.Layer{Array{Parallax.Object, 1}}, Symbol, Float64})
    precompile(Tuple{typeof(Base.indexed_iterate), Array{Int64, 1}, Int64, Int64})
    precompile(Tuple{typeof(Base.:(==)), UInt8, Int64})
    precompile(Tuple{typeof(Base.collect), Base.Generator{Base.UnitRange{Int64}, getfield(Parallax, Symbol("##5#6"))}})
    precompile(Tuple{typeof((Base.Broadcast).broadcasted), (Base.Broadcast).DefaultArrayStyle{1}, typeof(identity), Base.RefValue{Type{Int64}}, (Base.Broadcast).Broadcasted{(Base.Broadcast).DefaultArrayStyle{1}, Nothing, typeof(Base.:+), Tuple{(Base.Broadcast).Broadcasted{(Base.Broadcast).DefaultArrayStyle{1}, Nothing, typeof(Base.:*), Tuple{Array{Float64, 1}, Float64}}, Array{Float64, 1}}}})
    precompile(Tuple{typeof(Base.:(*)), Int32, Float64})
    precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Symbol, Gloria.Event}, Int64})
    precompile(Tuple{typeof(Base.manifest_deps_get), String, Base.PkgId, String})
    precompile(Tuple{typeof(Base.identify_package), String})
    precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Symbol, Gloria.Event}, Int64, Int64})
    precompile(Tuple{typeof(Base.Cartesian.lreplace!), QuoteNode, Base.Cartesian.LReplace{String}})
    precompile(Tuple{typeof(Base.collect_to_with_first!), Array{Parallax.Object, 1}, Parallax.Object, Base.Generator{Base.UnitRange{Int64}, getfield(Parallax, Symbol("##5#6"))}, Int64})
    precompile(Tuple{getfield(Base, Symbol("##open#294")), (Base.Iterators).Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(identity), (getfield(Base, Symbol("##643#644"))){String, String}, String})
    precompile(Tuple{typeof(Base.promote_typeof), Gloria.Layer{Array{Parallax.Object, 1}}, Gloria.Layer{Array{Parallax.Object, 1}}, Gloria.Layer{Array{Parallax.Object, 1}}})
    precompile(Tuple{typeof(Base.sizeof), Type{Int}})
    precompile(Tuple{typeof(Base.Broadcast.broadcastable), Type{Int64}})
    precompile(Tuple{typeof(Base.promote_typeof), Gloria.Layer{Array{Parallax.Controls, 1}}, Gloria.Layer{Array{Parallax.Object, 1}}, Gloria.Layer{Array{Parallax.Object, 1}}})
    precompile(Tuple{typeof(Base.convert), Type{Real}, Float64})
    precompile(Tuple{typeof(Base.Cartesian.exprresolve), QuoteNode})
    precompile(Tuple{typeof(Base.randn), Random.MersenneTwister})
    precompile(Tuple{typeof(Base.collect), Base.Generator{Base.StepRange{Int64, Int64}, getfield(Parallax, Symbol("##3#4"))}})
    precompile(Tuple{typeof(Base.collect_to_with_first!), Array{Gloria.Layer{Array{Parallax.Object, 1}}, 1}, Gloria.Layer{Array{Parallax.Object, 1}}, Base.Generator{Base.StepRange{Int64, Int64}, getfield(Parallax, Symbol("##3#4"))}, Int64})
    precompile(Tuple{typeof(Base.append!), Gloria.Layer{Array{Parallax.Object, 1}}, Array{Parallax.Object, 1}})
    precompile(Tuple{typeof(Base.:(*)), Array{Float64, 2}, Array{Float64, 1}})
end
