function _precompile_()
    precompile(Tuple{getfield(Base, Symbol("##643#644")){String, String}, Base.IOStream})
    precompile(Tuple{Type{Base.Val{x} where x}, Symbol})
    precompile(Tuple{Type{Base.Dict{String, Gloria.AbstractResource}}})
    precompile(Tuple{Type{NamedTuple{(:target_render_speed, :target_update_speed), T} where T<:Tuple}, Tuple{Float64, Float64}})
    precompile(Tuple{Type{Base.Generator{I, F} where F where I}, getfield(Parallax, Symbol("##5#6")), Base.UnitRange{Int64}})
    precompile(Tuple{Type{Base.Generator{I, F} where F where I}, getfield(Parallax, Symbol("##3#4")), Base.StepRange{Int64, Int64}})
    precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Base.round), Tuple{Base.RefValue{Type{Int64}}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(+)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(*)), Tuple{Array{Float64, 1}, Float64}}, Array{Float64, 1}}}}})
    precompile(Tuple{Type{NamedTuple{(:show,), T} where T<:Tuple}, Tuple{Bool}})
    precompile(Tuple{Type{Symbol}, Symbol, Int})
    precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Base.:(*)), Tuple{Array{Float64, 1}, Float64}})
    precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Base.:(+)), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Base.:(*)), Tuple{Array{Float64, 1}, Float64}}, Array{Float64, 1}}})
    precompile(Tuple{Type{Base.Val{x} where x}, UInt32})
end
